// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.Infrastructure.Persistence;

#nullable disable

namespace Shopping.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    partial class ShoppingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopping.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "starter-coffee",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A balanced ground coffee for everyday brewing.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Starter Coffee",
                            PriceAmount = 8.99m,
                            Slug = "starter-coffee",
                            StockQuantity = 100,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "ceramic-mug",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A durable ceramic mug for hot drinks.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Ceramic Mug",
                            PriceAmount = 12.50m,
                            Slug = "ceramic-mug",
                            StockQuantity = 50,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "travel-tumbler",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A stainless steel tumbler for drinks on the move.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Travel Tumbler",
                            PriceAmount = 18.00m,
                            Slug = "travel-tumbler",
                            StockQuantity = 40,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "espresso-beans",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "Whole beans roasted for a rich espresso profile.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Espresso Beans",
                            PriceAmount = 11.25m,
                            Slug = "espresso-beans",
                            StockQuantity = 120,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "breakfast-tea",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A strong black tea blend for morning brewing.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Breakfast Tea",
                            PriceAmount = 6.75m,
                            Slug = "breakfast-tea",
                            StockQuantity = 90,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "glass-teapot",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A clear teapot with an infuser for loose leaf tea.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Glass Teapot",
                            PriceAmount = 24.99m,
                            Slug = "glass-teapot",
                            StockQuantity = 25,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "pour-over-kit",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A starter kit for manual pour over coffee.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Pour Over Kit",
                            PriceAmount = 29.50m,
                            Slug = "pour-over-kit",
                            StockQuantity = 30,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "milk-frother",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A compact electric frother for milk and alternatives.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Milk Frother",
                            PriceAmount = 16.99m,
                            Slug = "milk-frother",
                            StockQuantity = 45,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "coffee-filters",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "Compostable paper filters for pour over brewing.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Coffee Filters",
                            PriceAmount = 4.25m,
                            Slug = "coffee-filters",
                            StockQuantity = 200,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "cold-brew-bottle",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A glass bottle with filter for overnight cold brew.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Cold Brew Bottle",
                            PriceAmount = 21.00m,
                            Slug = "cold-brew-bottle",
                            StockQuantity = 20,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "digital-scale",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A precise kitchen scale for consistent brewing.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Digital Scale",
                            PriceAmount = 19.95m,
                            Slug = "digital-scale",
                            StockQuantity = 35,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "gift-card",
                            CreatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "GBP",
                            Description = "A digital gift card for the online shop.",
                            IsAvailable = true,
                            IsPublished = true,
                            Name = "Gift Card",
                            PriceAmount = 25.00m,
                            Slug = "gift-card",
                            StockQuantity = 999,
                            UpdatedUtc = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Shopping.Infrastructure.Persistence.Entities.ProductImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "DisplayOrder");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "starter-coffee-primary",
                            AltText = "Starter Coffee product image",
                            BlobName = "products/starter-coffee.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "starter-coffee"
                        },
                        new
                        {
                            Id = "ceramic-mug-primary",
                            AltText = "Ceramic Mug product image",
                            BlobName = "products/ceramic-mug.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "ceramic-mug"
                        },
                        new
                        {
                            Id = "travel-tumbler-primary",
                            AltText = "Travel Tumbler product image",
                            BlobName = "products/travel-tumbler.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "travel-tumbler"
                        },
                        new
                        {
                            Id = "espresso-beans-primary",
                            AltText = "Espresso Beans product image",
                            BlobName = "products/espresso-beans.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "espresso-beans"
                        },
                        new
                        {
                            Id = "breakfast-tea-primary",
                            AltText = "Breakfast Tea product image",
                            BlobName = "products/breakfast-tea.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "breakfast-tea"
                        },
                        new
                        {
                            Id = "glass-teapot-primary",
                            AltText = "Glass Teapot product image",
                            BlobName = "products/glass-teapot.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "glass-teapot"
                        },
                        new
                        {
                            Id = "pour-over-kit-primary",
                            AltText = "Pour Over Kit product image",
                            BlobName = "products/pour-over-kit.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "pour-over-kit"
                        },
                        new
                        {
                            Id = "milk-frother-primary",
                            AltText = "Milk Frother product image",
                            BlobName = "products/milk-frother.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "milk-frother"
                        },
                        new
                        {
                            Id = "coffee-filters-primary",
                            AltText = "Coffee Filters product image",
                            BlobName = "products/coffee-filters.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "coffee-filters"
                        },
                        new
                        {
                            Id = "cold-brew-bottle-primary",
                            AltText = "Cold Brew Bottle product image",
                            BlobName = "products/cold-brew-bottle.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "cold-brew-bottle"
                        },
                        new
                        {
                            Id = "digital-scale-primary",
                            AltText = "Digital Scale product image",
                            BlobName = "products/digital-scale.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "digital-scale"
                        },
                        new
                        {
                            Id = "gift-card-primary",
                            AltText = "Gift Card product image",
                            BlobName = "products/gift-card.svg",
                            DisplayOrder = 0,
                            IsPrimary = true,
                            ProductId = "gift-card"
                        });
                });

            modelBuilder.Entity("Shopping.Infrastructure.Persistence.Entities.ProductImageEntity", b =>
                {
                    b.HasOne("Shopping.Infrastructure.Persistence.Entities.ProductEntity", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shopping.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
