@{
    Repository = "<github-owner>/<github-repository>"
    Branch = "master"
    WorkloadName = "shopping"
    # Optional. Defaults to a safe slug derived from the canonical GitHub owner/repository.
    # Set explicitly when a different stable installation label is required.
    InstanceName = ""
    Environments = @("dev", "test", "prod")

    Azure = @{
        TenantId = "<azure-resource-tenant-id>"
        SubscriptionId = "<azure-subscription-id>"
        DeploymentRoles = @(
            "Contributor"
            "Role Based Access Control Administrator"
        )
    }

    ExternalId = @{
        TenantId = "<external-id-tenant-id>"
        Domain = "<tenant-name>.onmicrosoft.com"
        Instance = "https://<tenant-name>.ciamlogin.com/"
        WebRedirectUris = @(
            "https://localhost:7262/signin-oidc"
            "http://localhost:5140/signin-oidc"
        )
        # Optional public ingress origins. Leave empty to use the deterministic
        # App Service origin generated by bootstrap and consumed by Bicep.
        PublicWebBaseUrls = @{
            dev = ""
            test = ""
            prod = ""
        }
        # Optional. Use -PromptForExternalIdValues to select a tenant user interactively.
        BootstrapAdminUserObjectId = ""
    }

    GitHub = @{
        ProductionReviewers = @("<github-user>")
        RulesetName = "protected master"
    }

    SqlAdministratorLogin = "sqladminuser"
}
